# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Admin\Documents\PSoC Creator\CE224899_PSoC4_CapSense_Hybrid_Buttons01\CapSense_15_Buttons.cydsn\CapSense_15_Buttons.cyprj
# Date: Tue, 24 Dec 2019 15:10:56 GMT
#set_units -time ns
create_clock -name {CapSense_ModClk(FFB)} -period 10625 -waveform {0 5312.5} [list [get_pins {ClockBlock/ff_div_2}]]
create_clock -name {EZI2C_SCBCLK(FFB)} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/ff_div_0}]]
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {CapSense_ModClk} -source [get_pins {ClockBlock/hfclk}] -edges {1 255 511} [list]
create_generated_clock -name {EZI2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 3 7} [list]


# Component constraints for C:\Users\Admin\Documents\PSoC Creator\CE224899_PSoC4_CapSense_Hybrid_Buttons01\CapSense_15_Buttons.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Admin\Documents\PSoC Creator\CE224899_PSoC4_CapSense_Hybrid_Buttons01\CapSense_15_Buttons.cydsn\CapSense_15_Buttons.cyprj
# Date: Tue, 24 Dec 2019 15:10:55 GMT
